name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Python dependencies cache
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install gcovr 5.0
        run: |
          pip install gcovr==5.0

      - name: Install and configure build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          cmake -DCMAKE_C_FLAGS="-fprofile-arcs -ftest-coverage" -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage" -S . -B build

      - uses: SonarSource/sonarcloud-github-c-cpp@v2
        with:
          build-wrapper: true
          build-wrapper-output: ${{ env.BUILD_WRAPPER_OUT_DIR }}

      - name: Build project
        run: |
          cmake --build build/ --config Debug

      - name: Run tests to generate coverage statistics
        run: |
          ./build/xpdf/pdftotext -raw ./c4611_sample_explain.pdf

      - name: Collect coverage into one XML report
        run: |
          gcovr --root . --sonarqube -o coverage.xml

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}" \
            --define sonar.coverageReportPaths=coverage.xml
